### ISSUE TITLE
Does not work correctly with Chrome 41

### ISSUE THREAD

**Issue by moronoron** [wjywbs/chrome-newtab-reloaded#19]
When Chrome 41 is set to open with a new tab page, newtab-reloaded does not show.  It does show if you then open a new tab though.

Also, when Chrome 41 is set to open several pages, the first click on new tab does not show newtab-reloaded, but the 2nd click on new tab does show newtab-reloaded (sometimes...this behavior might be inconsistent).

**Comment by wjywbs** [comment]
What operating system and version of this extension are you using? Can you try to update to the new 0.1.3 version, or attach a screenshot or console log when it does not work?

**Comment by wjywbs** [comment]
I reverted the recent fixes and published 0.1.4 to the web store.

**Comment by moronoron** [comment]
I was using 0.1.3.  0.1.4 seems to fix the issue.
