### ISSUE TITLE
Doesn't works on 44.0.2403.155

### ISSUE THREAD

**Issue by canvural** [wjywbs/chrome-newtab-reloaded#21]
Hi,

I recently updated to 44.0.2403.125. And it seems this extension does not work.

I can't find any error messages or something else to figure out what the problem is. Anybody else having this issue?

**Comment by WORMSS** [comment]
Version 44.0.2403.130 m (64-bit)
Works fine for me.
Though a few days ago, I did have a scenario where 3 (separate) occasions in 2 days it loaded up a stripped down version of the Google New Tab Page. But a simple refresh sorted it.

I didn't have a reliable way to re-produce it, so I never reported it. (Not happened since)

**Comment by canvural** [comment]
Hmm, it still does not work for me.

And in the `chrome://extensions/` page i see `background page (Inactive)`. Maybe this have something to do with the issue.

**Comment by WORMSS** [comment]
The normal state of the background page is Inactive. It is only when the New Tab Page needs information that a normal webpage would not have access to that it requires the background page to be active. (Eg, accessing the most visited or cached fav-icons/thumbnails of websites), once it supplies that information, it goes back to Inactive.

**Comment by canvural** [comment]
Oh, i see.

I'm upgrading Chrome now. Maybe this will fix it.

**Comment by canvural** [comment]
Upgraded to `44.0.2403.155 (64-bit`, still no luck.

**Comment by wjywbs** [comment]
Could you please check:

1. This extension only works when Google is the default search engine.
2. Try to disable other new tab page related apps if this one does not load.

**Comment by canvural** [comment]
@wjywbs Yes, i read the troubleshoot section. I use Google and i don't use any other tab extension/app.

**Comment by wjywbs** [comment]
OK, I hope this is the last question: What is the title of the developer tools in inspect elements? For me, it's "Developer Tools - https://www.google.com/_/chrome/newtab-serviceworker.js". Could you also check if there are errors in the console?

**Comment by canvural** [comment]
In the new tab page, title is "Developer Tools - chrome-search://local-ntp/local-ntp.html"

And there are no errors.

**Comment by wjywbs** [comment]
So the issue is that Google's new tab page doesn't load on your Chrome. Could you check the link of the Google search engine in Settings->Manage Search Engines? This is a reference: https://github.com/wjywbs/chrome-newtab-reloaded/issues/6#issuecomment-41148787

**Comment by canvural** [comment]
I have the url starting with `{google:baseURL}`. But its slightly different at the end

    {google:baseURL}search?q=%s&{google:RLZ}{google:originalQueryForSuggestion}{google:assistedQueryStats}{google:searchFieldtrialParameter}{google:bookmarkBarPinned}{google:searchClient}{google:sourceId}{google:instantExtendedEnabledParameter}{google:omniboxStartMarginParameter}{google:contextualSearchVersion}ie={inputEncoding}

**Comment by wjywbs** [comment]
If you can find a way to load Google's new tab page, this issue will be solved. Another possible method is to click "add new user" button in the Settings and install this extension in that new user https://github.com/wjywbs/chrome-newtab-reloaded/issues/6#issuecomment-37100166.

Link to Google's new tab page:
https://www.google.com/_/chrome/newtab

**Comment by canvural** [comment]
It just works now. :+1: 

Strange.

**Comment by alvinrxg** [comment]
though here is closed. i think the problem in chromium Version 47.0.2497.0 (64-bit) could be posted here.

```
Navigated to https://www.google.de/_/chrome/newtab?espv=2&ie=UTF-8
SW registered
Fetch API cannot load chrome-extension://jliilhbdldnjbdbpajaakhpjpahnopbn/newtab.htm. URL scheme "chrome-extension" is not supported.
The FetchEvent for "chrome-extension://jliilhbdldnjbdbpajaakhpjpahnopbn/newtab.htm" resulted in a network error response: the promise was rejected.
Uncaught (in promise) TypeError: Failed to fetch
    at TypeError (native)
    at https://www.google.de/_/chrome/newtab-serviceworker.js:44:16
GET chrome-extension://jliilhbdldnjbdbpajaakhpjpahnopbn/newtab.htm net::ERR_FAILED
GET https://www.google.de/gen_204?atyp=i&ct=backbutton&cad=&ei=eyzgVcbgL4r5UsXIqPAI&zx=1440807248219 net::ERR_BLOCKED_BY_CLIENT
GET chrome-search://thumb/https://banking.sparkasse-hannover.de/ net::ERR_FAILED
GET chrome-search://thumb/http://www.stepstone.de/ net::ERR_FAILED
POST https://play.google.com/log?format=json net::ERR_BLOCKED_BY_CLIENT
```
and here's the screenshot, which shows more detailed info http://ww1.sinaimg.cn/large/772454c5gw1evj67um7eij20s80hldh3.jpg

**Comment by wjywbs** [comment]
@alvinrxg Yes, this is a known issue that this extension is broken in Chrome 46+. The upstream bug report is at https://code.google.com/p/chromium/issues/detail?id=517181.
