### ISSUE TITLE
Chrome 46 fails to run this extension

### ISSUE THREAD

**Issue by wjywbs** [wjywbs/chrome-newtab-reloaded#22]
The service worker on the Google's new tab page intercepts the ajax to chrome-extension:// urls from this extension and fails to fetch them, so this extension doesn't overwrite Google's new tab page.

Upstream bug report is at https://code.google.com/p/chromium/issues/detail?id=517181.

**Comment by limasierra** [comment]
Hi,

I'm still facing this issue on Chrome 45 on Linux (Version 45.0.2454.101 (64-bit)). I disabled all the other extensions, so there should be no interference. Any help?

Regards

**Comment by wjywbs** [comment]
If it doesn't run on Chrome 45, it's different issue, probably #21.

What is the title of the developer tools in inspect elements? For me, it's "Developer Tools - https://www.google.com/_/chrome/newtab-serviceworker.js". Could you also check if there are errors in the console?

Clearing browsing data of google website might also help. Also, using vpn in other country may change the new tab page's link and cause bugs in the browser.
