### ISSUE TITLE
Doesn't work on Chrome 48

### ISSUE THREAD

**Issue by shadowlmd** [wjywbs/chrome-newtab-reloaded#25]
Extension stopped working after Chrome upgraded to 48.

**Comment by shadowlmd** [comment]
It started working today suddenly. I didn't change anything, there were no Chrome updates. Magic.

**Comment by wjywbs** [comment]
Do you still have this issue now or occasionally?

**Comment by shadowlmd** [comment]
Nope. Works like a charm.
