### ISSUE TITLE
This extension may be taken down on August 1

### ISSUE THREAD

**Issue by wjywbs** [wjywbs/chrome-newtab-reloaded#27]
I received this email from chromewebstore-dev-support@google.com on July 5. The counter argument would be: this extension does not redirect search requests, and the new tab page API is insufficient to provide all the features needed in this extension.

---

Updates to Chrome Web Store Policy

Dear Developer,
Protecting users and user choice have been long-standing principles of Google's core philosophy. That is why three years ago, Chrome released an extension-based Settings Overrides API for Chrome on Windows that ensures all users have notice and control over any settings change that take place in their browser. Earlier this year, we implemented the same API for macOS.

Starting August 1, the only compliant way to programmatically change the startup page, homepage, search provider setting, or any other setting that has an API is via the appropriate API. If your extension affects changes to any of these functions, it must use the API.

Extensions that have been using the Webrequest API (or other mechanisms) to redirect search requests from the new tab page or the omnibox, must now use the search provider and/or new tab page API. After August 1st, extensions redirecting search requests from the new tab page or omnibox without using these APIs will be removed from the store.

Extensions that perform automatic redirections from a web page URL must display a prominent notice informing the user of the redirection. For example, if an extension redirects search queries from www.google.com (or any other search provider), the extension's notice must:

Be prominent: large, conspicuous, and close in proximity to the search box and on the search engine results page
Be timely: shown prior to the user executing the search
Be persistent: the prominent notice (including the name) cannot automatically disappear or be dismissable; it must show up every time, not just prior to the first redirect
Must show the name of the extension (and the brand of search engine, if different) and what will happen
Not look similar to a system or Chrome dialog box or user-interface element; for example, disclosures in yellow bars that look similar to Chrome's yellow ("butter") bars are not permitted.
Extensions must also comply with other Chrome Web Store policies and Google's Unwanted Software Policy.

Sincerely,

Chrome Web Store Team
You have received this mandatory service announcement to update you about important changes to your account.

© 2016 Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA

**Comment by WORMSS** [comment]
I am sorry to hear this.. I first heard about this was happening a month or so again, I was hoping due to the reasons you listed that this would not affect this extension.. :crossed_fingers:

**Comment by kurtextrem** [comment]
@wjywbs This mail has reached every developer in the Chrome Webstore. I don't think it specifically targets your extension.
