### ISSUE TITLE
not work in Canary

### ISSUE THREAD

**Issue by vampireprincess** [wjywbs/chrome-newtab-reloaded#28]
Hi till yesterday it worked well in Chrome Canary but somehow today it stopped I tried everything but it seems I cant repair it.
However in Chrome it work fine also in Chromium works fine.

**Comment by kurtextrem** [comment]
Yeah, I also wonder what's going on. This change has now reached Chrome Dev.

**Comment by wjywbs** [comment]
I reproduced this issue on canary. The workaround seems to be changing default search engine to other than Google and change it back.

The long term solution is to make this extension as a search engine option ("New Tab Reloaded"), so we can provide our own new tab page. You may try to select Bing search engine and see their custom new tab page in Chrome.

**Comment by WORMSS** [comment]
Bummer, I've just restarted chrome (On v60 now).. and it's finally hit... The blank front page.

I tried toggling the search engine. It does indeed bring up a different new-tab-page.. When I went back to google, it failed again.. Sad times.

![image](https://user-images.githubusercontent.com/1384537/29910600-696c10b2-8e22-11e7-8787-6db5bdcb9f60.png)

**Comment by nothinglastsforever** [comment]
I can also repro as of v62.0.3201.0 (Official Build) canary (64-bit)., @wjywbs I tried your solution but it does not work. 

Is this related to what I brought to your attention, @wjywbs? https://github.com/wjywbs/chrome-newtab-reloaded/issues/20

Super disappointed and extremely annoyed with the Chrome team (what's new).

**Comment by wjywbs** [comment]
@WORMSS 6992ffd5ca05931b85f05ec354b5496f4382b623 should fix the blank most visited page. I'm going to publish this new version to the web store.

**Comment by WORMSS** [comment]
Nice, I would get the commit and run it as a development mode, but I am currently neck deep in a major refactor of our own software.. Hopefully the new version wont take longer than a few hours to propagate through the webstore.

**Comment by WORMSS** [comment]
I can confirm v0.1.10 works.

**Comment by WORMSS** [comment]
@wjywbs I am seeing a disconnect between thumb nails at the moment.. 
It's not even a case of 1 item being missing and everything is off by 1.. 
It's a mismatch of thumbnails. 

Without giving away my most visited list, I'l try to describe it.. (Current'y in the standard 4 wide, 2 deep layout)

![image](https://user-images.githubusercontent.com/1384537/30099034-4a191944-92dc-11e7-9de8-efb28a943d75.png)

The thumbnail in position Yellow, Brown and Violet have no matching text on display
And text Brown, Light Yellow and Grey have no matching thumbnail on display.

**Comment by wjywbs** [comment]
This is strange. I'm not sure if adef9b7cba69dd3c6972e790d28dcabf1d846f74 caused this. Does the default ntp show the same problem after disabling this extension?

**Comment by wjywbs** [comment]
After updating to Chrome 61 that was released today, this extension seems to be completely broken.

**Comment by WORMSS** [comment]
Default NTP has correct thumb nails to titles..

BUT, it has shown what the problem seems to be..
As both NewTabReloaded and NewTabPage show the same thumbnails in the same order.
But now that the titles match the thumbnails, it is easier to see that they do seem to be a better match of what my "most visited" would/should be.

So it seems the thumbnails are correct... 
But it's the titles (and the url) that seem to be wrong..

I hope this helps.

- Colin

**Comment by wjywbs** [comment]
I just found this link chrome://ntp-tiles-internals to show all tiles. Does deleting one tile and clicking the "restore all" link fix this issue?

**Comment by WORMSS** [comment]
problem remains

**Comment by wjywbs** [comment]
@WORMSS Could you try aaf2c1f35c5b3f0e6b1295225f359fc91b9f0e92 locally and see if the problem resolves? You may still encounter issues when removing thumbnails.

**Comment by WORMSS** [comment]
Seems to do the trick. Even works with `delete > resort all`.

Great work 👍

**Comment by nothinglastsforever** [comment]
@wjywbs ~~I haven't seen anyone mention this, but are the "Other devices" and "Recently closed" menus expected to disappear on v0.1.12 and Chrome v61.0.3163.9? Or am I the only one who used this extension for these features?~~

Disregard. I'm an idiot. I forgot to enable _Show "recently closed tabs" and "other device pages"
( Available in Chrome 37 and later )_ in the options. The workaround to set bing as default then switch back to google only worked once and has stopped working again.

**Comment by Nuchaz** [comment]
I can't seem to delete tiles anymore. I click the X and it just pops back up. Now I got a porn site on my tile list and I can't get rid of it, lol.

**Comment by wjywbs** [comment]
As mentioned in aaf2c1f35c5b3f0e6b1295225f359fc91b9f0e92, only the first 8 most visited items can be removed. This is a new limitation after Chrome 60.

The not loading issue will be further tracked in #29.
